name: Publish Website to CPanel

on:
  push:
    branches:
      - main

jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 2

      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.SERVER }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

  Migrate-Database:
    name: Run PHP Artisan Migrate
    runs-on: ubuntu-latest
    needs: FTP-Deploy-Action
    steps:
      - name: SSH into Server
        uses: appleboy/ssh-action/
        with:
          host: ${{ secrets.SERVER }}
          username: shorcjrk
          port: 21098
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/shorcjrk/public_html
            php artisan migrate
