name: Laravel SSH Deploy

on:
  push:
    branches:
      - main

jobs:
  SSH-Deploy-Action:
    name: SSH-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 2

      - name: Set up SSH
        uses: appleboy/setup-ssh-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: SSH Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            php artisan migrate --force
